services:
    kirim-aja-backend:
        build: .
        container_name: kirim-aja-backend
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - '3000:3000'
        depends_on:
            - mysql
            - redis
        networks:
            - kirim-aja-network
